name: shallow_landslider
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy >= 2.0
  - scipy
  - pandas
  - pyarrow
  - xarray
  - zarr >= 3,<4
  - matplotlib
  - seaborn
  - scikit-image
  - richdem
  - landlab
  - jupyterlab         # ← required to run notebooks
  - ipykernel          # ← required so the environment appears as a kernel
  - tqdm
  - pip
  - pip:
      - astropy
      - bmi-topography
